// This file is generated by PhobosCompiler v0.0.1

#include <malloc.h>
#include <stdint.h>
#include <string.h>

typedef uint8_t Phobos_Bool;
typedef uint8_t Phobos_Byte;
typedef int8_t Phobos_Int8;
typedef int16_t Phobos_Int16;
typedef int32_t Phobos_Int32;
typedef int64_t Phobos_Int64;
typedef uint8_t Phobos_UInt8;
typedef uint16_t Phobos_UInt16;
typedef uint32_t Phobos_UInt32;
typedef uint64_t Phobos_UInt64;

typedef struct String
{
    Phobos_Int32 length;
    Phobos_Byte bytes[];
} String;
struct Array__Phobos_Byte__
{
    Phobos_Int32 length;
    Phobos_Byte elements[];
};
Phobos_Int32 Array__Phobos_Byte____Length(struct Array__Phobos_Byte__ *array) { return array->length; }
struct Array__Phobos_Byte__ *String__ToByteArray(String *str)
{
    struct Array__Phobos_Byte__ *array = malloc(str->length + sizeof(Phobos_Int32));
    array->length = str->length;
    memcpy(array->elements, str->bytes, str->length);
    return array;
}

struct Phobos_Char
{
    Phobos_Byte _byte;
};

typedef uint32_t Phobos_Compiler_TokenKind;

struct Phobos_Compiler_Pos
{
    Phobos_Int32 _value;
};

struct Phobos_Compiler_Token
{
    Phobos_Compiler_TokenKind _kind;
    struct Phobos_Compiler_Pos _start;
    struct Phobos_Compiler_Pos _end;
    String *_lexeme;
};

struct Phobos_Compiler_Scanner
{
    struct Array__Phobos_Byte__ *_code;
    Phobos_Int32 _offset;
    struct Phobos_Char _currentChar;
    struct Phobos_Compiler_Token _token;
    Phobos_Bool _atEndOfSource;
};

struct Phobos_Char Phobos_Char_1(Phobos_Byte byte)
{
    return (struct Phobos_Char){._byte = byte};
}

void Phobos_Compiler_Scanner__NextChar(struct Phobos_Compiler_Scanner *self)
{
    if (self->_atEndOfSource)
        return;
    if (self->_offset >= Array__Phobos_Byte____Length(self->_code))
    {
        self->_atEndOfSource = 1;
        return;
    }

    self->_currentChar = Phobos_Char_1(self->_code->elements[self->_offset]);
    self->_offset += 1;
}

struct Phobos_Compiler_Scanner *Phobos_Compiler_Scanner_1(struct Array__Phobos_Byte__ *code)
{
    struct Phobos_Compiler_Scanner *scanner = malloc(sizeof(struct Phobos_Compiler_Scanner));
    scanner->_code = code;
    scanner->_offset = 0;
    scanner->_atEndOfSource = 0;
    scanner->_token = (struct Phobos_Compiler_Token){0};
    Phobos_Compiler_Scanner__NextChar(scanner);
    return scanner;
}

Phobos_Bool Phobos_Char__IsAlpha(struct Phobos_Char *self)
{
    if (((self->_byte >= 65) && (self->_byte <= 90)) || ((self->_byte >= 97) && (self->_byte <= 122)))
        return 1;
    return 0;
}

void Phobos_Compiler_Scanner__ScanIdentifier(struct Phobos_Compiler_Scanner *self)
{
}

Phobos_Bool Phobos_Char__IsDigit(struct Phobos_Char *self)
{
    if ((self->_byte >= 48) && (self->_byte <= 57))
        return 1;
    return 0;
}

void Phobos_Compiler_Scanner__ScanNumber(struct Phobos_Compiler_Scanner *self)
{
}

void Phobos_Compiler_Scanner__NextToken(struct Phobos_Compiler_Scanner *self)
{
    if (self->_atEndOfSource)
        return;
    if (Phobos_Char__IsAlpha(&self->_currentChar))
        Phobos_Compiler_Scanner__ScanIdentifier(self);
    else if (Phobos_Char__IsDigit(&self->_currentChar))
        Phobos_Compiler_Scanner__ScanNumber(self);
}

void Phobos_Compiler_Main()
{
    String *_t1 = malloc(5 + sizeof(int32_t));
    _t1->length = 5;
    memcpy(_t1->bytes, "1 + 2", 5);
    String *src = _t1;
    struct Phobos_Compiler_Scanner *scanner = Phobos_Compiler_Scanner_1(String__ToByteArray(src));
    Phobos_Compiler_Scanner__NextToken(scanner);
}

int main(int argc, char **argv)
{
    Phobos_Compiler_Main();
}
