// This file is generated by PhobosCompiler v0.0.1

#include <stdint.h>

// Primitive types
typedef int32_t Phobos_Int32;
typedef int64_t Phobos_Int64;

// Forward function prototypes

void InitialiseGlobals() {
}

void Phobos_Compiler_Main() {
Phobos_Int32 a = 5;
}

int main(int argc, char **argv) {
Phobos_Compiler_Main();
}
